services:
  - type: web
    name: portfolio
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_DEFAULT_REGISTRY
        value: https://registry.npmjs.org/
